### ISSUE TITLE
allow non literal values to be prefixed

### ISSUE THREAD

**Issue by salzhrani** [UXtemple/autoprefix#2]
currently if the value is an expression, prefixing skips.

```
{ transform: 2 * val }
```

is there a workaround or a fix ?

thanks

**Comment by dariocravero** [comment]
@salzhrani could you provide a failing test for this?

The way I see it in your example, shouldn't `transform` be whatever value it can be before even hitting autoprefix?

E.g. (from a repl):

```
> var autoprefix = require('autoprefix');
'use strict'
> var val=10; autoprefix({transform: 2 * val})
{ WebkitTransform: '20', MsTransform: '20', transform: '20' }
```

Am I missing something?

**Comment by salzhrani** [comment]
Sorry, I think it might be an issue with the plugin not autoprefix. Submitted a test there.

**Comment by dariocravero** [comment]
:) cool, thanks
